routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Golongan
Route::resource('admin/golongan', 'Web\Admin\GolonganController', ['as' => 'admin']);
//Pendidikan
Route::resource('admin/pendidikan', 'Web\Admin\PendidikanController', ['as' => 'admin']);
//Jabatan
Route::resource('admin/jabatan', 'Web\Admin\JabatanController', ['as' => 'admin']);
//Pegawai
Route::resource('admin/pegawai', 'Web\Admin\PegawaiController', ['as' => 'admin']);
//History
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);
//Izin
Route::resource('admin/izin', 'Web\Admin\IzinController', ['as' => 'admin']);
Route::post('admin/izin/cetak', 'Web\Admin\IzinController@cetak')->name('admin.izin.cetak');
//Cuti
Route::resource('admin/cuti', 'Web\Admin\CutiController', ['as' => 'admin']);
Route::post('admin/cuti/cetak', 'Web\Admin\CutiController@cetak')->name('admin.cuti.cetak');
//Naik
Route::resource('admin/naikjabatan', 'Web\Admin\NaikController', ['as' => 'admin']);
//Mutasi
Route::resource('admin/mutasi', 'Web\Admin\MutasiController', ['as' => 'admin']);
//Gaji
Route::resource('admin/gaji', 'Web\Admin\GajiController', ['as' => 'admin']);
Route::post('admin/gaji/cetak', 'Web\Admin\GajiController@cetak')->name('admin.gaji.cetak');
//Absensi
Route::resource('admin/absensi', 'Web\Admin\AbsensiController', ['as' => 'admin']);
Route::post('admin/absensi/cetak', 'Web\Admin\AbsensiController@cetak')->name('admin.absensi.cetak');




//PIMPINAN
//Beranda
Route::resource('pimpinan/beranda', 'Web\Pimpinan\BerandaController', ['as' => 'pimpinan']);
//Pegawai
Route::resource('pimpinan/pegawai', 'Web\Pimpinan\PegawaiController', ['as' => 'pimpinan']);
Route::get('pimpinan/pegawai/cetak/{id}', 'Web\Pimpinan\PegawaiController@cetak')->name('pimpinan.pegawai.cetak');
Route::get('cetak-semua-pegawai', 'Web\Pimpinan\PegawaiController@cetak_all')->name('cetak-semua-pegawai');



//PEGAWAI
//Beranda
Route::resource('pegawai/beranda', 'Web\Pegawai\BerandaController', ['as' => 'pegawai']);
//Cuti
Route::resource('pegawai/cuti', 'Web\Pegawai\CutiController', ['as' => 'pegawai']);

app/Gaji.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gaji extends Model
{
    protected $guarded = [];
    protected $dates = ['created_at'];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/Web/Admin/GajiController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Gaji;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\GajiRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GajiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $tahun = 2018;
        $pegawai = User::where('id', 'not like', 1)->where('id', 'not like', 2)->orderBy('name', 'ASC')->get()->all();
        $data = Gaji::orderBy('tahun', 'DESC')->orderBy('id', 'DESC')->get()->all();
        return view('admin.gaji.beranda', compact('data', 'no', 'pegawai', 'tahun'));
    }

    public function create()
    {
        //
    }
    public function cetak(Request $request)
    {
        $tahun = $request->tahun;
        $bulan = $request->bulan;

        $data = Gaji::where('tahun', $tahun)->where('bulan', $bulan)->get();
        // dd($data);

        $no = 1;

        return view('admin.gaji.cetak_bulan', compact('data', 'bulan', 'tahun'));
    }

    public function store(GajiRequest $request)
    {
        $data = $request->all();
        Gaji::create($data);
        $user = User::findOrFail($request->user_id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Gaji " . $user->name;
        History::create($histori);

        $notification = array(
            'message' => 'Data Gaji "' . $user->name . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.gaji.index')->with($notification);
    }

    public function show($id)
    {
        $data = Gaji::findOrFail($id);
        return view('admin.gaji.cetak', compact('data'));
    }

    public function edit($id)
    {
        $pegawai = User::where('id', 'not like', 1)->where('id', 'not like', 2)->orderBy('name', 'ASC')->get()->all();
        $data = Gaji::findOrFail($id);
        return view('admin.gaji.edit', compact('data', 'pegawai'));
    }

    public function update(GajiRequest $request, $id)
    {
        $data = Gaji::findOrFail($id);
        $data->update($request->all());
        $user = User::findOrFail($request->user_id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Gaji " . $user->name;
        History::create($histori);

        $notification = array(
            'message' => 'Data Gaji "' . $user->name . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.gaji.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Gaji::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Gaji " . $data->user->name;
        History::create($histori);

        $notification = array(
            'message' => 'Data Gaji "' . $data->user->name . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.gaji.index')->with($notification);
    }
}

resources/views/admin/gaji/beranda.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Gaji')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Gaji Pegawai
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.gaji.cetak') }}" class="form-horizontal" method="POST" target="_blank">
                @csrf

                <div class="col-sm-2">
                    <select class="form-control" name="tahun">
                        {{ $last= date('Y')-3 }}
                        {{ $now = date('Y') }}

                        @for ($i = $now; $i >= $last; $i--)
                        <option value="{{ $i }}">{{ $i }}</option>
                        @endfor
                    </select>
                </div>
                <div class="col-sm-2">
                    <select class="form-control" name="bulan">
                        <option value="Januari">Januari</option>
                        <option value="Februari">Februari</option>
                        <option value="Maret">Maret</option>
                        <option value="April">April</option>
                        <option value="Mei">Mei</option>
                        <option value="Juni">Juni</option>
                        <option value="Juli">Juli</option>
                        <option value="Agustus">Agustus</option>
                        <option value="September">September</option>
                        <option value="Oktober">Oktober</option>
                        <option value="November">November</option>
                        <option value="Desember">Desember</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Cetak</button>
            </form>
            <br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Gaji Pegawai</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.gaji.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="user_id">
                                        @foreach($pegawai as $pe)
                                        <option value="{{$pe->id}}">{{$pe->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Tahun</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="tahun">
                                        {{ $last= date('Y')-3 }}
                                        {{ $now = date('Y') }}

                                        @for ($i = $now; $i >= $last; $i--)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Bulan</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="bulan">
                                        <option value="Januari">Januari</option>
                                        <option value="Februari">Februari</option>
                                        <option value="Maret">Maret</option>
                                        <option value="April">April</option>
                                        <option value="Mei">Mei</option>
                                        <option value="Juni">Juni</option>
                                        <option value="Juli">Juli</option>
                                        <option value="Agustus">Agustus</option>
                                        <option value="September">September</option>
                                        <option value="Oktober">Oktober</option>
                                        <option value="November">November</option>
                                        <option value="Desember">Desember</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Total Gaji</label>

                                <div class="col-sm-8">
                                    <input type="number" name="gaji" class="form-control" placeholder="Total Gaji">
                                    <small class="text-danger">{{ $errors->first('gaji') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Tahun</th>
                                <th>Bulan</th>
                                <th>Nama</th>
                                <th>Gaji</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->tahun}}</td>
                                <td>{{ $item->bulan}}</td>
                                <td>{{ $item->user->name}}</td>
                                <td>{{ $item->gaji}}</td>
                                <td align="center">
                                    <form action="{{ route('admin.gaji.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-primary" href="{{ route('admin.gaji.show',$item->id) }}" target="_blank">Cetak</a>
                                        <a class="btn btn-success" href="{{ route('admin.gaji.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/gaji/cetak.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Data Gaji - {{$data->user->name}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="{{ asset('itlabil/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
        @media print {
            @page {
                size: auto !important
            }
        }

        .samping {
            padding: 15px 15px;
        }

        body {
            font-family: 'Source Sans Pro', sans-serif;
            margin: 15px 15px;
        }

        .kanankiri {
            text-align: justify;
        }

        .tengah {
            text-align: center;
        }

        .hr4 {
            border: solid 1px;
        }
    </style>
</head>

<body onload="window.print()">
    <!-- onload="window.print()" -->
    <div class="container">
        <table width="100%" border=1 style="margin-bottom: 20px;">
            <tbody>
                <tr>
                    <td>
                        <table width="100%">
                            <tr>
                                <td align="right" width="25%">
                                    <img src="{{asset('itlabil/image/default/logo.png')}}" alt="" width="100px">
                                </td>
                                <td align="center" width="650%">
                                    <b>
                                        <h4>PT. PERKEBUNAN NUSANTARA VII</h4>
                                        Perincian Gaji Take Home Pay<br>
                                    </b>
                                </td>
                                <td width="25%"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="25%">DETAIL</td>
                                <td width="20%">: GAJI BULANAN</td>
                                <td width="20%">Nama</td>
                                <td width="35%">: {{$data->user->name}}</td>
                            </tr>
                            <tr>
                                <td>Bulan</td>
                                <td>: {{$data->created_at->format('m/Y')}}</td>
                                <td>NIK SAP</td>
                                <td>: {{$data->user->nip}}</td>
                            </tr>
                            <tr>
                                <td>Status Kar</td>
                                <td>: Karpel - Tetap</td>
                                <td>Posisi</td>
                                <td>: {{$data->user->jabatan}}</td>
                            </tr>
                            <tr>
                                <td>Gol Kar</td>
                                <td>: {{$data->user->golongan}}</td>
                                <td>Unit Kerja</td>
                                <td>: Wabe-Tanaman-Afdeling 4</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="75%">TOTAL GAJI</td>
                                <td>Rp. {{ number_format($data->gaji, 0, ".", ".")}}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="30%" align="center">
                                    PENERIMA,<br><br><br><br>
                                    {{$data->user->name}}
                                </td>
                                <td width="40%"></td>
                                <td width="30%" align="center" valign="top">PTPN VII Unit Wabe</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</body>

</html>

resources/views/admin/gaji/cetak_bulan.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Data Gaji - {{$bulan}} {{$tahun}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="{{ asset('itlabil/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
        @media print {
            @page {
                size: auto !important
            }
        }

        .samping {
            padding: 15px 15px;
        }

        body {
            font-family: 'Source Sans Pro', sans-serif;
            margin: 15px 15px;
        }

        .kanankiri {
            text-align: justify;
        }

        .tengah {
            text-align: center;
        }

        .hr4 {
            border: solid 1px;
        }
    </style>
</head>

<body onload="window.print()">
    <!-- onload="window.print()" -->
    <div class="container">
        @foreach($data as $item)
        <table width="100%" border=1 style="margin-bottom: 20px; margin-right:10px">
            <tbody>
                <tr>
                    <td>
                        <table width="100%">
                            <tr>
                                <td align="right" width="25%">
                                    <img src="{{asset('itlabil/image/default/logo.png')}}" alt="" width="100px">
                                </td>
                                <td align="center" width="650%">
                                    <b>
                                        <h4>PT. PERKEBUNAN NUSANTARA VII</h4>
                                        Perincian Gaji Take Home Pay<br>
                                    </b>
                                </td>
                                <td width="25%"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="25%">DETAIL</td>
                                <td width="20%">: GAJI BULANAN</td>
                                <td width="20%">Nama</td>
                                <td width="35%">: {{$item->user->name}}</td>
                            </tr>
                            <tr>
                                <td>Bulan</td>
                                <td>: {{$item->created_at->format('m/Y')}}</td>
                                <td>NIK SAP</td>
                                <td>: {{$item->user->nip}}</td>
                            </tr>
                            <tr>
                                <td>Status Kar</td>
                                <td>: Karpel - Tetap</td>
                                <td>Posisi</td>
                                <td>: {{$item->user->jabatan}}</td>
                            </tr>
                            <tr>
                                <td>Gol Kar</td>
                                <td>: {{$item->user->golongan}}</td>
                                <td>Unit Kerja</td>
                                <td style="padding-right: 20px;">: Wabe-Tanaman-Afdeling 4</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="65%">TOTAL GAJI</td>
                                <td>Rp. {{ number_format($item->gaji, 0, ".", ".")}}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding-left: 5px;">
                        <table width="100%" style="margin: 5px 5px;">
                            <tr>
                                <td width="30%" align="center">
                                    PENERIMA,<br><br><br><br>
                                    {{$item->user->name}}
                                </td>
                                <td width="40%"></td>
                                <td width="30%" align="center" valign="top">PTPN VII Unit Wabe</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
        <div style='page-break-after:always'></div>
        @endforeach
    </div>

</body>

</html>

resources/views/admin/gaji/edit.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Gaji')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Gaji
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Gaji</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.gaji.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="user_id">
                                        <option value="{{$data->user_id}}">{{$data->user->name}}</option>
                                        @foreach($pegawai as $pe)
                                        <option value="{{$pe->id}}">{{$pe->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Tahun</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="tahun">
                                        <option value="{{ $data->tahun }}">{{ $data->tahun }}</option>
                                        {{ $last= date('Y')-3 }}
                                        {{ $now = date('Y') }}

                                        @for ($i = $now; $i >= $last; $i--)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                        @endfor
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Bulan</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="bulan">
                                        <option value="{{ $data->bulan }}">{{ $data->bulan }}</option>
                                        <option value="Januari">Januari</option>
                                        <option value="Februari">Februari</option>
                                        <option value="Maret">Maret</option>
                                        <option value="April">April</option>
                                        <option value="Mei">Mei</option>
                                        <option value="Juni">Juni</option>
                                        <option value="Juli">Juli</option>
                                        <option value="Agustus">Agustus</option>
                                        <option value="September">September</option>
                                        <option value="Oktober">Oktober</option>
                                        <option value="November">November</option>
                                        <option value="Desember">Desember</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Total Gaji</label>

                                <div class="col-sm-8">
                                    <input type="number" value="{{$data->gaji}}" name="gaji" class="form-control" placeholder="Total Gaji">
                                    <small class="text-danger">{{ $errors->first('gaji') }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/gaji')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection