routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Golongan
Route::resource('admin/golongan', 'Web\Admin\GolonganController', ['as' => 'admin']);
//Pendidikan
Route::resource('admin/pendidikan', 'Web\Admin\PendidikanController', ['as' => 'admin']);
//Jabatan
Route::resource('admin/jabatan', 'Web\Admin\JabatanController', ['as' => 'admin']);
//Pegawai
Route::resource('admin/pegawai', 'Web\Admin\PegawaiController', ['as' => 'admin']);
//History
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);
//Izin
Route::resource('admin/izin', 'Web\Admin\IzinController', ['as' => 'admin']);
Route::post('admin/izin/cetak', 'Web\Admin\IzinController@cetak')->name('admin.izin.cetak');
//Cuti
Route::resource('admin/cuti', 'Web\Admin\CutiController', ['as' => 'admin']);
Route::post('admin/cuti/cetak', 'Web\Admin\CutiController@cetak')->name('admin.cuti.cetak');
//Naik
Route::resource('admin/naikjabatan', 'Web\Admin\NaikController', ['as' => 'admin']);
//Mutasi
Route::resource('admin/mutasi', 'Web\Admin\MutasiController', ['as' => 'admin']);
//Gaji
Route::resource('admin/gaji', 'Web\Admin\GajiController', ['as' => 'admin']);
Route::post('admin/gaji/cetak', 'Web\Admin\GajiController@cetak')->name('admin.gaji.cetak');
//Absensi
Route::resource('admin/absensi', 'Web\Admin\AbsensiController', ['as' => 'admin']);
Route::post('admin/absensi/cetak', 'Web\Admin\AbsensiController@cetak')->name('admin.absensi.cetak');




//PIMPINAN
//Beranda
Route::resource('pimpinan/beranda', 'Web\Pimpinan\BerandaController', ['as' => 'pimpinan']);
//Pegawai
Route::resource('pimpinan/pegawai', 'Web\Pimpinan\PegawaiController', ['as' => 'pimpinan']);
Route::get('pimpinan/pegawai/cetak/{id}', 'Web\Pimpinan\PegawaiController@cetak')->name('pimpinan.pegawai.cetak');
Route::get('cetak-semua-pegawai', 'Web\Pimpinan\PegawaiController@cetak_all')->name('cetak-semua-pegawai');



//PEGAWAI
//Beranda
Route::resource('pegawai/beranda', 'Web\Pegawai\BerandaController', ['as' => 'pegawai']);
//Cuti
Route::resource('pegawai/cuti', 'Web\Pegawai\CutiController', ['as' => 'pegawai']);

app/Absensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    protected $guarded = [];
    protected $dates = ['tanggal'];
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/Web/Admin/AbsensiController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Absensi;
use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\AbsensiRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AbsensiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = User::where('id', 'not like', 1)->where('id', 'not like', 2)->orderBy('name', 'ASC')->get()->all();
        return view('admin.absensi.beranda', compact('data', 'no'));
    }
    public function cetak(Request $request)
    {
        $tgl = $request->tanggal.' 00:00:00';

        $data = Absensi::where('tanggal', $tgl)->get();
        // dd($data);

        $no = 1;

        return view('admin.absensi.cetak_hari', compact('data', 'tgl', 'no'));
    }

    public function create()
    {
        $no = 1;
        $data = User::where('id', 'not like', 1)->where('id', 'not like', 2)->orderBy('name', 'ASC')->get()->all();
        return view('admin.absensi.create', compact('data', 'no'));
    }

    public function store(Request $request)
    {
        $user_id = $request->user_id;
        $tanggal = $request->tanggal;
        $ket = $request->ket;

        foreach ($user_id as $key => $user_value) {
            $userS[] = Absensi::create([
                'user_id' => $user_value,
                'tanggal' => $tanggal[$key],
                'ket' => $ket[$key]
            ]);
        }

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Absensi.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Absensi berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.absensi.index')->with($notification);
    }

    public function show($id)
    {
        $no = 1;
        $data = User::findOrFail($id);
        return view('admin.absensi.show', compact('data', 'no'));
    }

    public function edit($id)
    {
        $data = Absensi::findOrFail($id);
        return view('admin.absensi.edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $data = Absensi::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Absensi.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Absensi berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.absensi.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Absensi::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Absensi.";
        History::create($histori);

        $notification = array(
            'message' => 'Data Absensi berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.absensi.index')->with($notification);
    }
}

resources/views/admin/absensi/beranda.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Absensi')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-8">
            <form action="{{ route('admin.absensi.cetak') }}" class="form-horizontal" method="POST" target="_blank">
                @csrf

                <div class="col-sm-3">
                    <input type="date" name="tanggal" class="form-control" placeholder="Tanggal">
                </div>
                <button type="submit" class="btn btn-primary">Cetak</button>
            </form>
            <br>
        </div>
        <div class="col-md-4" align="right">
            <a href="{{ route('admin.absensi.create') }}" class="btn btn-primary">+ Absensi</a><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Absensi</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>NIP</th>
                                <th>Nama</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->nip}}</td>
                                <td>{{ $item->name}}</td>
                                <td align="center">
                                    <a class="btn btn-primary" href="{{ route('admin.absensi.show',$item->id) }}">Lihat</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/absensi/cetak_hari.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Data Absensi - {{tanggal_local($tgl)}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="{{ asset('itlabil/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
        @media print {
            @page {
                size: auto !important
            }
        }

        .samping {
            padding: 15px 15px;
        }

        body {
            font-family: 'Source Sans Pro', sans-serif;
            margin: 15px 15px;
        }

        .kanankiri {
            text-align: justify;
        }

        .tengah {
            text-align: center;
        }

        .hr4 {
            border: solid 1px;
        }
    </style>
</head>

<body onload="window.print()">
    <!-- onload="window.print()" -->
    <div class="container">
        <table width="100%" style="margin-bottom: 20px;">
            <tbody>
                <tr>
                    <td align="center" width="120px">
                        <img src="{{asset('itlabil/image/default/logo.png')}}" alt="" width="100px">
                    </td>
                    <td align="center">
                        <b>
                            <h4>PT. PERKEBUNAN NUSANTARA VII</h4>
                            AFDELING IV<br>
                            Unit Wayberulu Desa Sukaraja Kec. Gedongtataan 35366<br>
                            PESAWARAN
                        </b>
                    </td>
                </tr>
            </tbody>
        </table>
        <hr class="hr4">
        <table width="100%" style="margin-bottom: 20px;">
            <tbody>
                <tr>
                    <td>Data Absensi Pegawai {{tanggal_local($tgl)}}</td>
                </tr>
            </tbody>
        </table>
        <table border="1" width="100%" style="margin-top: 20px;">
            <thead>
                <tr>
                    <th style="padding-left: 10px;">No</th>
                    <th style="padding-left: 10px;">NIP</th>
                    <th style="padding-left: 10px;">Nama</th>
                    <th style="padding-left: 10px;">Keterangan</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td style="padding-left: 10px;">{{ $no++ }}</td>
                    <td style="padding-left: 10px;">{{ $item->user->nip}}</td>
                    <td style="padding-left: 10px;">{{ $item->user->name}}</td>
                    <td style="padding-left: 10px;">{{ $item->ket}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

</body>

</html>

resources/views/admin/absensi/create.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Absensi')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Absensi</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.absensi.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-12">
                            @foreach($data as $item)
                            <div class="form-group">
                                <label class="col-sm-3">{{$item->name}}</label>
                                <input type="hidden" name="tanggal[{{$no}}]" value="<?php echo date('Y-m-d'); ?>" />
                                <input type="hidden" name="user_id[{{$no}}]" value="{{$item->id}}">
                                <div class="col-sm-2">
                                    <input type="radio" id="hadir" name="ket[{{$no}}]" value="Hadir"><label for="Hadir" style="margin-left: 5px;"> Hadir</label>
                                </div>
                                <div class="col-sm-2">
                                    <input type="radio" id="izin" name="ket[{{$no}}]" value="Izin"><label for="Izin" style="margin-left: 5px;"> Izin</label>
                                </div>
                                <div class="col-sm-2">
                                    <input type="radio" id="cuti" name="ket[{{$no}}]" value="Cuti"><label for="Cuti" style="margin-left: 5px;"> Cuti</label>
                                </div>
                                <div class="col-sm-3">
                                    <input type="radio" id="thadir" name="ket[{{$no}}]" value="Tidak Hadir"><label for="Tidak Hadir" style="margin-left: 5px;"> Tidak Hadir</label>
                                </div>
                            </div>
                            @php $no++ @endphp
                            @endforeach
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/absensi')}}" class="btn btn-default  pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/absensi/edit.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Absensi')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Absensi</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.absensi.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Nama</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="user_id">
                                        <option value="{{$data->user->id}}">{{$data->user->name}}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Tanggal</label>

                                <div class="col-sm-8">
                                    <input type="date" value="{{$data->tanggal->format('Y-m-d')}}" name="tanggal" class="form-control" placeholder="Tanggal">
                                    <small class="text-danger">{{ $errors->first('tanggal') }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="tahun" class="col-sm-4 control-label">Keterangan</label>

                                <div class="col-sm-8">
                                    <select class="form-control" name="ket">
                                        <option value="{{$data->ket}}">{{$data->ket}}</option>
                                        <option value="Hadir">Hadir</option>
                                        <option value="Izin">Izin</option>
                                        <option value="Cuti">Cuti</option>
                                        <option value="Tidak Hadir">Tidak Hadir</option>
                                    </select>
                                </div>
                            </div>

                            <a href="{{url('admin/absensi')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/absensi/show.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Absensi')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Absensi
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Absensi - {{$data->name}}</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Tanggal</th>
                                <th>Keterangan</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data->absensi as $item)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{ $item->tanggal->format('d-m-Y') }}</td>
                                <td>{{$item->ket}}</td>
                                <td>
                                    <form action="{{ route('admin.absensi.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.absensi.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <a href="{{url('admin/absensi')}}" class="btn btn-default">Kembali</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection