routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);


//ADMIN
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Golongan
Route::resource('admin/golongan', 'Web\Admin\GolonganController', ['as' => 'admin']);
//Pendidikan
Route::resource('admin/pendidikan', 'Web\Admin\PendidikanController', ['as' => 'admin']);
//Jabatan
Route::resource('admin/jabatan', 'Web\Admin\JabatanController', ['as' => 'admin']);
//Pegawai
Route::resource('admin/pegawai', 'Web\Admin\PegawaiController', ['as' => 'admin']);
//History
Route::resource('admin/history', 'Web\Admin\HistoryController', ['as' => 'admin']);
//Izin
Route::resource('admin/izin', 'Web\Admin\IzinController', ['as' => 'admin']);
Route::post('admin/izin/cetak', 'Web\Admin\IzinController@cetak')->name('admin.izin.cetak');
//Cuti
Route::resource('admin/cuti', 'Web\Admin\CutiController', ['as' => 'admin']);
Route::post('admin/cuti/cetak', 'Web\Admin\CutiController@cetak')->name('admin.cuti.cetak');
//Naik
Route::resource('admin/naikjabatan', 'Web\Admin\NaikController', ['as' => 'admin']);
//Mutasi
Route::resource('admin/mutasi', 'Web\Admin\MutasiController', ['as' => 'admin']);
//Gaji
Route::resource('admin/gaji', 'Web\Admin\GajiController', ['as' => 'admin']);
Route::post('admin/gaji/cetak', 'Web\Admin\GajiController@cetak')->name('admin.gaji.cetak');
//Absensi
Route::resource('admin/absensi', 'Web\Admin\AbsensiController', ['as' => 'admin']);
Route::post('admin/absensi/cetak', 'Web\Admin\AbsensiController@cetak')->name('admin.absensi.cetak');




//PIMPINAN
//Beranda
Route::resource('pimpinan/beranda', 'Web\Pimpinan\BerandaController', ['as' => 'pimpinan']);
//Pegawai
Route::resource('pimpinan/pegawai', 'Web\Pimpinan\PegawaiController', ['as' => 'pimpinan']);
Route::get('pimpinan/pegawai/cetak/{id}', 'Web\Pimpinan\PegawaiController@cetak')->name('pimpinan.pegawai.cetak');
Route::get('cetak-semua-pegawai', 'Web\Pimpinan\PegawaiController@cetak_all')->name('cetak-semua-pegawai');



//PEGAWAI
//Beranda
Route::resource('pegawai/beranda', 'Web\Pegawai\BerandaController', ['as' => 'pegawai']);
//Cuti
Route::resource('pegawai/cuti', 'Web\Pegawai\CutiController', ['as' => 'pegawai']);

app/Pendidikan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pendidikan extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Web/Admin/PendidikanController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\History;
use App\Http\Controllers\Controller;
use App\Http\Requests\PendidikanRequest;
use App\Pendidikan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PendidikanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = Pendidikan::where('pendidikan','not like','-')->orderBy('id', 'ASC')->get()->all();
        return view('admin.pendidikan.beranda', compact('data', 'no'));
    }

    public function create()
    {
        //
    }

    public function store(PendidikanRequest $request)
    {
        $data = $request->all();
        Pendidikan::create($data);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Tambah";
        $histori['desc_info'] = "Data Pendidikan " . $request->pendidikan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pendidikan "' . $request->pendidikan . '" berhasil ditambah.',
            'alert-type' => 'info'
        );

        return redirect()->route('admin.pendidikan.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = Pendidikan::findOrFail($id);
        return view('admin.pendidikan.edit', compact('data'));
    }

    public function update(PendidikanRequest $request, $id)
    {
        $data = Pendidikan::findOrFail($id);
        $data->update($request->all());

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Ubah";
        $histori['desc_info'] = "Data Pendidikan " . $request->pendidikan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pendidikan "' . $request->pendidikan . '" berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.pendidikan.index')->with($notification);
    }

    public function destroy($id)
    {
        $data = Pendidikan::findOrFail($id);

        // HISTORI
        $histori['user'] = Auth::user()->name;
        $histori['info'] = "Hapus";
        $histori['desc_info'] = "Data Pendidikan " . $data->pendidikan;
        History::create($histori);

        $notification = array(
            'message' => 'Data Pendidikan "' . $data->pendidikan . '" berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.pendidikan.index')->with($notification);
    }
}

resources/views/admin/pendidikan/beranda.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Pendidikan')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Pendidikan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Pendidikan</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.pendidikan.store') }}" class="form-horizontal" method="POST">
                        @csrf

                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Pendidikan</label>

                                <div class="col-sm-10">
                                    <input type="text" name="pendidikan" class="form-control" placeholder="Pendidikan">
                                    <small class="text-danger">{{ $errors->first('pendidikan') }}</small>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
                <hr>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Pendidikan</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->pendidikan}}</td>
                                <td align="center">
                                    <form action="{{ route('admin.pendidikan.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.pendidikan.edit',$item->id) }}">Ubah</a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/pendidikan/edit.blade.php
@extends('layouts.admin')
@section('title', 'Admin - Pendidikan')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Pendidikan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Pendidikan</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.pendidikan.update', $data->id) }}" class="form-horizontal" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Pendidikan</label>

                                <div class="col-sm-10">
                                    <input type="text" value="{{$data->pendidikan}}" name="pendidikan" class="form-control" placeholder="Pendidikan">
                                    <small class="text-danger">{{ $errors->first('pendidikan') }}</small>
                                </div>
                            </div>

                            <a href="{{url('admin/pendidikan')}}" class="btn btn-default">Kembali</a>
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection